### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by appsforartists** [mwjkwan/portfolio#3]
Hi Melissa,

It looks like the links are broken in your portfolio.
- https://melissa-kwan.com/projects/cs51
- https://melissa-kwan.com/projects/page-layout-algorithm
- https://melissa-kwan.com/projects/hodp
- https://melissa-kwan.com/resume

Since you're using React to render the pages, I suspect you need to add this chunk to your firebase.json to ensure that the right HTML file is served if the user visits a link:
```json
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ],
```
https://firebase.google.com/docs/hosting/full-config

**Comment by mwjkwan** [comment]
Hi Brenton,

Thanks for pointing this out! As of now, the site is static, so I used the HashRouter workaround. 

By the way, Ambidex looks awesome. I've been reading more about isomorphic Javascript due to this issue — are there any resources that you'd recommend?

Best,
Melissa

**Comment by appsforartists** [comment]
It's been a long time since I played with it - I wouldn't even know what to recommend.
